# Generated by Django 2.2.6 on 2019-11-28 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='listings',
            new_name='properties',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='listing_id',
            new_name='property_id',
        ),
    ]
