# Generated by Django 2.2.6 on 2019-11-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20191122_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='job_description',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
