# Generated by Django 2.2.6 on 2019-11-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertie',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
